### PR TITLE
chore(fluent-bit): upgrade to 1.8.15

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

##### Description

Fill in your description here.

---

##### Checklist

- [ ] Changelog updated

###### Testing performed

- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by pdelewski — APPROVED** [review]

**Review by astencel-sumo — CHANGES_REQUESTED** [review]
This version of Fluent Bit crashes on configurations that 1.6.10 works fine with. Are we sure we want to do this?

**Comment by sumo-drosiek** [comment]
What configuration?

**Comment by ReillyBrogan** [comment]
Might as well use 1.9.7 instead now. Hopefully this can be updated given that 1.6.10 is now more than a year and a half old.

**Comment by swiatekm-sumo** [comment]
@sumo-drosiek do we still want to do this? We ran into problems every time we tried to upgrade, and at this point it's probably easier to use otel.

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek do we still want to do this? We ran into problems every time we tried to upgrade, and at this point it's probably easier to use otel.

I doubt about fluent-bit stability. `1.6.10` was the most stable so far. I believe we can close it for now and recommend to use OpenTelemetry Collector. Also there is nothing which can stop customers from using newer version

**Pull request closed without merging**
