### PR TITLE
Add scc for setup job

### PR DESCRIPTION
**Pull request by sumo-drosiek**
###### Description

Add scc for setup job

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by frankreno — APPROVED** [review]
Goof find! LGTM

**Review by perk-sumo — APPROVED** [review]
Megusta.

**Review by vsinghal13 — COMMENTED** [review]
@frankreno I wonder how we were able to deploy the collection on your openshift cluster without hitting this issue? 
Also, I think we don't need an additional `scc` as the exact same `scc` already exists
[here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/templates/scc.yaml) and we can just add the security context to the setup job, unless I am missing something?

**Comment by frankreno** [comment]
> @frankreno I wonder how we were able to deploy the collection on your openshift cluster without hitting this issue?
> Also, I think we don't need an additional `scc` as the exact same `scc` already exists
> [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/master/deploy/helm/sumologic/templates/scc.yaml) and we can just add the security context to the setup job, unless I am missing something?

When I handed the cluster to you guys, I may have had an SCC in there as I was playing with straight-up YAML outside the helm chart.  I believe the SCC is not created until after the hook completes.  It doesn't have the annotation to install as part of the pre-install hook.

**Comment by sumo-drosiek** [comment]
@frankreno @vsinghal13 
> When I handed the cluster to you guys, I may have had an SCC in there

That is my guess too. When I created scc by hand, the setup has been finished correctly

**Comment by sumo-drosiek** [comment]
> Also, I think we don't need an additional `scc` as the exact same `scc` already exists

I decided to keep separate scc for setup job as we do with other templates

**Comment by sumo-drosiek** [comment]
I tried to use only `setup-scc`, but then only telegraf-operator pod was created

**Pull request merged**
