### PR TITLE
feat: update memory_limiter processor configs

### PR DESCRIPTION
**Pull request by aboguszewski-sumo**
Change `memory_limiter` usage:

- removed in events collector, as we can allow crashes there; essentially it can be seen as a breaking change
- increased the limit to 90% in other otelcol instances

### Checklist

- [X] Changelog updated or skip changelog label added
- [ ] Documentation updated
- [ ] Template tests added for new features
- [ ] Integration tests added or modified for major features

### CODE REVIEW

**Review by kkujawa-sumo — APPROVED** [review]
LGTM but please wait with merge for one more approval

**Comment by aboguszewski-sumo** [comment]
IMO we can wait for the standup to discuss this, as this breaking change might be controversial.

**Review by swiatekm-sumo — APPROVED** [review]
I don't think this is a breaking change, but we can wait for more opinions before merging.

**Comment by aboguszewski-sumo** [comment]
I am convinced now that it's not a breaking change. I changed the changelog entry.

**Pull request merged**
