### PR TITLE
feat: migrating to /var/log/pods path

### PR DESCRIPTION
**Pull request by pdelewski**
##### Description

Fill in your description here.

---

##### Checklist

- [ ] Changelog updated

###### Testing performed

- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
This is a breaking change, so it should be labelled appropriately and tagged with the v3 milestone.

**Comment by astencel-sumo** [comment]
Fixes #2171

**Review by sumo-drosiek — APPROVED** [review]
Please prepare migration in [sumologic-kubernetes-tools](https://github.com/SumoLogic/sumologic-kubernetes-tools/tree/c4f6d6b51f444958482c9bc20ff10ea5da1800d7/src/go/cmd/update-collection-v3)

**Review by sumo-drosiek — CHANGES_REQUESTED** [review]
For migration script

**Comment by pdelewski** [comment]
> Please prepare migration in [sumologic-kubernetes-tools](https://github.com/SumoLogic/sumologic-kubernetes-tools/tree/c4f6d6b51f444958482c9bc20ff10ea5da1800d7/src/go/cmd/update-collection-v3)

I will create ticket for that, to not forget

**Comment by perk-sumo** [comment]
Turns out this is expensive to do and we should just not do it at all.

**Pull request closed without merging**
