### PR TITLE
docs(troubleshoot): add solution for dns issue in otellogs

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

### Checklist

- [ ] Changelog updated or skip changelog label added
- [ ] Documentation updated
- [ ] Template tests added for new features
- [ ] Integration tests added or modified for major features

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
Under what circumstances does this happen exactly? Should we recommend setting this by default when using FIPS images, or maybe set it in the FIPS build?

**Comment by sumo-drosiek** [comment]
I would set it in the FIPS build, but until that we should have document it.

It happens for `alpine` with statically linked go libraries

**Comment by sumo-drosiek** [comment]
I saw this error every time using `0.69.0-fips` (vagrant, customer environment)

**Comment by swiatekm-sumo** [comment]
I'm wondering if we should add this to troubleshooting docs, given that we're going to enable this option for all FIPS builds.

**Comment by sumo-drosiek** [comment]
Documentation is going to be much faster available for customers than release and helm chart change

**Review by swiatekm-sumo — APPROVED** [review]

**Pull request merged**
