### PR TITLE
feat(opentelemetry): send information about k8s version

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Send k8s version with every request to Sumo Logic

### Checklist

- [ ] Changelog updated or skip changelog label added
- [ ] Documentation updated
- [ ] Template tests added for new features
- [ ] Integration tests added or modified for major features

### CODE REVIEW

**Comment by aboguszewski-sumo** [comment]
I can't find any documentation on the `client` option, where can I find it? It's neither in https://github.com/SumoLogic/sumologic-otel-collector nor contrib repo.

**Comment by sumo-drosiek** [comment]
@aboguszewski-sumo 

- https://github.com/SumoLogic/sumologic-otel-collector/blob/main/pkg/exporter/sumologicexporter/config.go#L65
- https://github.com/SumoLogic/sumologic-otel-collector/pull/1396

**Review by aboguszewski-sumo — APPROVED** [review]
LGTM, but we should update the readme in sumologic exporter.
Also, it seems that there is a redundant comment. I'll do it if I'll have time today.

**Comment by sumo-drosiek** [comment]
PR is open in otel collector repository

**Pull request merged**
