### PR TITLE
docs: mention prometheusInstanceNamespaces in documentation

### PR DESCRIPTION
**Pull request by sumo-drosiek**
###### Description

mention `prometheusInstanceNamespace`s in documentation for openshift

###### Testing performed

- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by pmalek-sumo — APPROVED** [review]

**Comment by sumo-drosiek** [comment]
```
 ERROR: 1 dead links found!
[✖] https://www.fluentd.org → Status: 0
```

**Comment by pmalek-sumo** [comment]
> ```
>  ERROR: 1 dead links found!
> [✖] https://www.fluentd.org → Status: 0
> ```

Not sure what's up with that. A rerun should fix it but I reckon it's not really a solution.

**Comment by sumo-drosiek** [comment]
It failed twice in a row, lets see now

**Comment by sumo-drosiek** [comment]
```
ERROR: 1 dead links found!
[✖] https://docs.fluentd.org/configuration/config-file#note-on-match-order → Status: 0
```

**Pull request merged**
