### PR TITLE
Set the default Prometheus scrape interval to 30s explicitly

### PR DESCRIPTION
**Pull request by perk-sumo**
###### Description

Fill in your description here.

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
I cannot find information about default value of this variable equal to 30s in the docs, by via the configuration site there is 30s, so :+1:

**Comment by sumo-drosiek** [comment]
I found it in the source code:
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/promcfg.go#L175

**Comment by samjsong** [comment]
As discussed on Slack, there can be some recording rules (ex: `node:node_cpu_utilisation:avg1m`) that will break if we increase the scrape interval. We should either come up with a way around that (increase the 1m in the recording rule?) or document this

**Comment by perk-sumo** [comment]
Fixed upstream with https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/665

**Pull request closed without merging**
