### PR TITLE
Remove the unused sumologic.traces.endpoint key (clean up otelcol conf after the #778 merge)

### PR DESCRIPTION
**Pull request by perk-sumo**
###### Description

Fill in your description here.

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
Can we split this enormous line to multiple lines to better track the git changes?

**Comment by perk-sumo** [comment]
@sumo-drosiek I've tried the naive split approach in abff23dea9ee2183ec84b142bb0dc9910221581c but it didn't work as it spawned the same file multiple times. Also Go templates cannot be multiline.

Because splitting it up is not trivial I'm going to merge as it is.

**Comment by perk-sumo** [comment]
It's smoke tested and ready for review /cc @pmm-sumo

**Comment by sumo-drosiek** [comment]
Thanks ❤️

**Pull request merged**
