### PR TITLE
feat: Add `fullnameOverride` chart parameter

### PR DESCRIPTION
**Pull request by astencel-sumo**
Example naming of pods for `fullnameOverride: overridename`:

```console
$ k get pods -n namespacename
NAME                                                   READY   STATUS        RESTARTS   AGE
overridename-fluentd-events-0                          0/1     Running       0          21s
overridename-fluentd-logs-0                            0/1     Running       0          21s
overridename-fluentd-metrics-0                         0/1     Running       0          21s
prometheus-releasename-kube-prometheu-prometheus-0     3/3     Running       1          21s
releasename-fluent-bit-k7xr6                           1/1     Running       0          21s
releasename-kube-prometheu-operator-59df9c69b6-97jb5   1/1     Running       0          21s
releasename-kube-state-metrics-567d57f874-p5gcg        1/1     Running       0          21s
releasename-prometheus-node-exporter-7x5f7             1/1     Running       0          21s
```

As you can see, the Fluentd pods include the override name, but the other pods don't - they belong to subcharts.

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
@astencel-sumo shouldnt't be `myname` in example?
Do other charts have similar configuration option to override them as well?

**Comment by astencel-sumo** [comment]
> @astencel-sumo shouldnt't be `myname` in example?
Good point, I tweaked the example and forgot to change the description :)

> Do other charts have similar configuration option to override them as well?
Yeah I went to check that yesterday.

In fact, most charts don't mention it in `values.yaml`, but they all seem to honor the `fullnameOverride` parameter.

- [fluent-bit](https://github.com/fluent/helm-charts/blob/fluent-bit-0.12.1/charts/fluent-bit/templates/_helpers.tpl#L15)
- [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-12.3.0/charts/kube-prometheus-stack/templates/_helpers.tpl#L15)

I'll try to re-run the collection with all those changed and will post the result here again.

**Comment by astencel-sumo** [comment]
Converting this PR to draft as I need to check something.

**Comment by astencel-sumo** [comment]
OK all good.

With the following overrides in `values.yaml`:

```yaml
fullnameOverride: k8c

fluent-bit:
  fullnameOverride: flbi

kube-prometheus-stack:
  fullnameOverride: kuprst

  kube-state-metrics:
    fullnameOverride: kustme

  prometheus-node-exporter:
    fullnameOverride: prnoex
```

the pods are named like this:

```console
$ kubectl -n namespacename get pods
NAME                               READY   STATUS    RESTARTS   AGE
flbi-blsxq                         1/1     Running   0          69s
k8c-fluentd-events-0               1/1     Running   0          69s
k8c-fluentd-logs-0                 1/1     Running   0          69s
k8c-fluentd-metrics-0              1/1     Running   0          69s
kuprst-operator-644bfc6db7-jq688   1/1     Running   0          69s
kustme-567c644446-k6q8b            1/1     Running   0          69s
prnoex-7rdp6                       1/1     Running   0          69s
prometheus-kuprst-prometheus-0     3/3     Running   1          66s
```

**Comment by sumo-drosiek** [comment]
Can we put in README as well?

**Review by sumo-drosiek — APPROVED** [review]

**Pull request merged**
