### PR TITLE
Add NodeSelector and Tolerations to both deployments

### PR DESCRIPTION
**Pull request by rvmiller89**
###### Description

Adds `nodeSelector` and `tolerations` to both deployments, from https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/255

###### Testing performed

- [x] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by djsly** [comment]
LGTM, thanks for doing what was needed to get the CI to pick it up

**Comment by djsly** [comment]
Should the Chart version be increased?

**Comment by rvmiller89** [comment]
Merging this will auto-generate the next alpha release (looks like it will be `v0.9.12-alpha`)

We'll kick off a round of end-to-end tests on our side, and assuming those pass we'll cut a new minor release `v0.10.0`.  Then we will update the Helm chart version in a second PR.

**Comment by djsly** [comment]
@rvmiller89 thanks for explaining the Build / Release process.

**Comment by rvmiller89** [comment]
It's available in Helm chart release 0.10.0 now: https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v0.10.0

**Pull request merged**
