### PR TITLE
chore: update telegraf to 1.21

### PR DESCRIPTION
**Pull request by swiatekm-sumo**
##### Description

1.14 is pretty old and contains quite a few vulnerabilities. I ran E2E tests on 1.21 and they passed without issue.

---

##### Checklist

Remove items which don't apply to your PR.

- [x] Changelog updated

###### Testing performed

- [X] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by pmalek-sumo — CHANGES_REQUESTED** [review]
Are there any breaking changes between 1.14.4 and 1.21.2?

I'd be more inclined to bump the operator version (that handles the image version itself) instead of bumping the image only.

**Comment by swiatekm-sumo** [comment]
> Are there any breaking changes between 1.14.4 and 1.21.2?
> 
> I'd be more inclined to bump the operator version (that handles the image version itself) instead of bumping the image only.
> 
> rel: https://github.com/influxdata/telegraf-operator/releases

No breaking changes in Telegraf itself: https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md. They seem to be following semantic versioning even if they don't state so explicitly in their documentation.

For Telegraf Operator, we're already running the latest version, and the default Telegraf version in its Helm Chart is 1.19. Do you recall if the 1.14.4 image was hosted on our ECR as a matter of policy, or if it was customized in some way?

**Review by pmalek-sumo — COMMENTED** [review]
I believe the changelog would need some rebasing. Wouldn't it? I wonder why github doesn't show it like that.

**Comment by swiatekm-sumo** [comment]
> I believe the changelog would need some rebasing. Wouldn't it? I wonder why github doesn't show it like that.

Good catch. Github does the right thing, since from its perspective there's no conflict in the diff, just an unrelated change in a different line (Unreleased -> 2.4.0).

**Review by pmalek-sumo — APPROVED** [review]

**Pull request merged**
