### PR TITLE
Adding ability to specify for annotations for serviceAccounts

### PR DESCRIPTION
**Pull request by nairb**
###### Description

Adds the ability to specify annotations for the serviceAccounts.  Resolves https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1644

---

###### Testing performed

- [x ] Redeploy fluentd and fluentd-events pods
- [x ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by sumo-drosiek — DISMISSED** [review]

**Comment by sumo-drosiek** [comment]
Hi, thank you for the contribution!

Could you add annotations for other service accounts and update chart's README.md please?

**Comment by nairb** [comment]
> Hi, thank you for the contribution!
> 
> Could you add annotations for other service accounts and update chart's README.md please?
> 
> other service accounts:
> 
> * [cleanup](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/b8418a5fca1f9788c9a176e0896dd25d3d19ccdf/deploy/helm/sumologic/templates/cleanup/serviceaccount.yaml)
> * [setup](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/b8418a5fca1f9788c9a176e0896dd25d3d19ccdf/deploy/helm/sumologic/templates/setup/serviceaccount.yaml)

Updated with your suggestions, thanks!

**Review by sumo-drosiek — APPROVED** [review]
Thank you once again!

**Comment by laupow** [comment]
Thank you @nairb, I was looking for this today. Very timely!

**Pull request merged**
