### PR TITLE
Prepare v2.1.0

### PR DESCRIPTION
**Pull request by perk-sumo**
###### Description

Fill in your description here.

---

###### Testing performed

- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by astencel-sumo — APPROVED** [review]
🎉

**Review by kkujawa-sumo — APPROVED** [review]
🎉

**Review by pmalek-sumo — COMMENTED** [review]
How about we include this ?

https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1536/files

**Comment by perk-sumo** [comment]
@pmalek-sumo thanks for pointing this out - let's include it in the next release

**Pull request merged**
