### PR TITLE
define resources for thanos sidecar

### PR DESCRIPTION
**Pull request by vsinghal13**
###### Description

Solves #862 
Ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosspec
###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by perk — CHANGES_REQUESTED** [review]
We should add the limits by ourselves as the upstream chart is not limited.

**Review by perk-sumo — CHANGES_REQUESTED** [review]
We should add the limits by ourselves as the upstream chart is not limited.

**Comment by vsinghal13** [comment]
Thanks @perk-sumo for adding the limits.

**Review by perk-sumo — APPROVED** [review]
👍

**Pull request merged**
