### PR TITLE
Revert removal of traces config

### PR DESCRIPTION
**Pull request by sumo-drosiek**
###### Description

Revert removal of traces config

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by mat-rumian** [comment]
Checked on k8s env. Works fine 🏅

**Review by mat-rumian — APPROVED** [review]

**Review by perk-sumo — APPROVED** [review]
LGTM, thanks!

**Comment by perk-sumo** [comment]
@sumo-drosiek please make sure CI passes before merge.

**Comment by perk-sumo** [comment]
Travis gives the following error:
https://travis-ci.org/github/SumoLogic/sumologic-kubernetes-collection/builds/722705120#L869
```
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/home/travis/.rvm/gems/ruby-2.5.3/gems/rake-12.3.3/lib" "/home/travis/.rvm/gems/ruby-2.5.3/gems/rake-12.3.3/lib/rake/rake_test_loader.rb" "test/plugin/test_filter_enhance_k8s_metadata.rb" "test/sumologic/kubernetes/test_cache_strategy.rb" "test/sumologic/kubernetes/test_connector.rb" "test/sumologic/kubernetes/test_reader.rb" "test/sumologic/kubernetes/test_service_monitor.rb" ]
/home/travis/.rvm/gems/ruby-2.5.3/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
Script error on line 54
The command "bash ci/build.sh" exited with 1.
```
We get the same error on `master` branch.

**Comment by perk-sumo** [comment]
CI fixed by https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/870

**Pull request merged**
