### PR TITLE
Labeling statefulset pvcs

### PR DESCRIPTION
**Pull request by mozz-lx**
###### Description

Enabled custom labels in fluentd logs, events, and metrics services.

Our company uses a strict admission controller policy where all our deploys, sts, jobs, pods, services, and PVC require a specific set of labels to allow the creation of those API objects.

---

###### Testing performed

- [x] Redeploy fluentd and fluentd-events pods
- [x] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by mozz-lx** [comment]
> @mozz-lx
> Shouldn't those labels go to the PVC definitions? Otherwise I feel that `statefulsetPVCLabels` name is not so intuitive

Hello @sumo-drosiek.

Thanks for the quick response! I'm open to any proper name for the `statefulsetPVCLabels` .

The PVC labels are inherited from `set.spec.selector.matchlabels` In the statefulset yaml file, not from `volumeClaimTemplates`. 

The current configuration in this PR generates something like this.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: xxxxxxx
  creationTimestamp: "2021-05-11T00:06:53Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: sumologic-sumologic-fluentd-metrics
    customlabelA: sumologic-collection
    customlabelB: operations
    customlabelC: container-orchestration
  name: buffer-sumologic-sumologic-fluentd-metrics-2
  namespace: sumo
  resourceVersion: "13528"
  selfLink: /api/v1/namespaces/sumo/persistentvolumeclaims/buffer-sumologic-sumologic-fluentd-metrics-2
  uid: 6aed4fdd-cfba-4e7a-9ff4-19007425cd6e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-6aed4fdd-cfba-4e7a-9ff4-19007425cd6e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

**Comment by pmalek-sumo** [comment]
> The PVC labels are inherited from `set.spec.selector.matchlabels` In the statefulset yaml file, not from `volumeClaimTemplates`.

Hi @mozz-lx ,

Do you mind referencing where is this coming from?

Just thinking out loud, I wonder: if these labels (that are to be inherited as you say by the pvcs) are set in `spec.selector.matchLabels` then does that somehow affect the pod "selection" that only have `app: {{ template "sumologic.labels.app.events.pod" . }}` defined (below in those yaml templates)?

**Comment by sumo-drosiek** [comment]
@mozz-lx 
I performed some local testing and
 - `matchLabels` has to match `spec.labels`
 - pvc labels are inherited from both `spec.labels` and `volumeClaimTemplates[].metadata.labels`
 
 Could you confirm this bahavior?

**Comment by pmalek-sumo** [comment]
> * pvc labels are inherited from both `spec.labels` and `volumeClaimTemplates[].metadata.labels`

Meaning the PVC will have a set of labels which is a sum of `spec.labels` and `volumeClaimTemplates[].metadata.labels`?

**Comment by sumo-drosiek** [comment]
@mozz-lx Thanks! It would be great if we stick to camelCase convention and use `pvcLabels` name

**Review by sumo-drosiek — APPROVED** [review]

**Pull request merged**
