### PR TITLE
Fix helper template variables

### PR DESCRIPTION
**Pull request by rvmiller89**
###### Description

In case we can't get https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/266 to work

###### Testing performed

- [x] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by djsly** [comment]
This goes with #265, since nindent is now used, the strings should now have leading spaces

**Comment by djsly** [comment]
@rvmiller89 when you get a chance to merge this, could we release an alpha tag to allow a public chart to be accessible? our logic is currently based on your public helm REPO and I don't have an easy way to inject local charts into my pipelines.

**Comment by rvmiller89** [comment]
@djsly I'll bring it up to the team about releasing Helm charts for alpha tag versions, right now I think our concern is that by publishing the alpha versions in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/gh-pages/index.yaml the default `helm install sumologic/sumologic` would download and install the latest alpha chart, rather than the stable tested release.

**Comment by djsly** [comment]
Thanks. 

I haven’t tried it for say but it looks like helm will not fetch pre release version in a repo anymore unless the -version is used to explicitly chose one. 

https://github.com/helm/helm/issues/2407

My gut feeling is that it should be safe to push some -alpha as long as they follow the pre-release format from SemVer2

**Pull request merged**
