### PR TITLE
chore: update Sumo Logic Kubernetes Setup to v3.15.1 (#3793)

### PR DESCRIPTION
**Pull request by rnishtala-sumo**

### CODE REVIEW

**Review by echlebek — APPROVED** [review]

**Comment by sumo-drosiek** [comment]
It requires this PR: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3780/files

**Comment by rnishtala-sumo** [comment]
@sumo-drosiek the setup image `3.15.1` doesn't seem to be compatible with helm chart v3

```
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/locals.tf': Permission denied
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/main.tf': Permission denied
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/providers.tf': Permission denied
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/resources.tf': Permission denied
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/variables.tf': Permission denied
Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/fields.tf': Permission denied
```

**Comment by rnishtala-sumo** [comment]
Found the issue, looks like the securityContext has changed for the job definitions.

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek the setup image `3.15.1` doesn't seem to be compatible with helm chart v3
> 
> ```
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/locals.tf': Permission denied
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/main.tf': Permission denied
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/providers.tf': Permission denied
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/resources.tf': Permission denied
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/variables.tf': Permission denied
> Test_Helm_Default_OT 2024-07-26T19:21:49Z logger.go:66: cp: can't create '/terraform/fields.tf': Permission denied
> ```

https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/3811#issuecomment-2252127450

**Pull request merged**
