### PR TITLE
Allow specifying pullSecrets

### PR DESCRIPTION
**Pull request by pmalek-sumo**
###### Description

This PR adds possibility to specify `pullSecrets` in order to authenticate with docker registry.
This can be done in order to e.g. overcome [hub.docker.com rate limiting](https://www.docker.com/increase-rate-limits)

Creating this secret is beyond the scope of our manuals and readme and user can refer to [Creating a Secret with a Docker config at kubernetes.io](https://kubernetes.io/docs/concepts/containers/images/#creating-a-secret-with-a-docker-config).

In order to use this secret for our dependencies, one can use the following customization in `values.yaml`:

* kube-prometheus-stack https://github.com/prometheus-community/helm-charts/blob/72a59c7bd3ff092cfd1bd2e654feaa62618a2b6f/charts/kube-prometheus-stack/values.yaml#L105-L109
* fluent-bit https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml#L5-L12
* metrics-server https://github.com/bitnami/charts/blob/master/bitnami/metrics-server/values.yaml#L22-L27
* telegraf-operator https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-operator/values.yaml#L23
* falco https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L3-L8

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
Please add some documentation about that

**Review by frankreno — APPROVED** [review]
LGTM.  In a seperate PR (or this one no preference) we should still add a new document about the options customers have to work around the rate limiting. This is one of them, hosting images in their own registry should be another we document.

**Comment by pmalek-sumo** [comment]
Added a section in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/image-pull-secrets/deploy/docs/Installation_with_Helm.md#authenticating-with-docker-registry.

We can work on a separate doc (covering hosting images in customers' registry as well) in a separate PR.

**Comment by perk-sumo** [comment]
There is a separate task for documentation how to deal with this situation: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1100

**Review by perk-sumo — APPROVED** [review]

**Pull request merged**
