### PR TITLE
Add configuration of fluent workers

### PR DESCRIPTION
**Pull request by sumo-drosiek**
###### Description

Allow to increase number of fluentd workers. It can help with some performance issues

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
@vsinghal13 @samjsong Do you see any cons for exposing workers to the configuration?

**Comment by vsinghal13** [comment]
Also, we need to verify if all the plugins that we use are compatible with multi-process workers. https://docs.fluentd.org/deployment/multi-process-workers#fluentd-cant-start-with-multi-process-workers-why

**Comment by sumo-drosiek** [comment]
Thank for pointing this out. I will create helm function for buffers to keep everything in one place as we discussed some time ago, and after that I will back to multi-workers :+1:

**Review by sumo-drosiek — COMMENTED** [review]
Remove auto-generated files due to #1052

**Comment by frankreno** [comment]
@sumo-drosiek - is this PR still relevant/needed?

**Comment by sumo-drosiek** [comment]
@frankreno It can increase the performance of the fluentd instance and after moving the buffer paths to the config.yaml it's easy to achive. I will perform some comparison test

**Comment by sumo-drosiek** [comment]
I updated the PR and tested the change.

So, fluentd with 2 workers and CPU limit increased to 2 works with about same performance like 2 fluentd pods, so there is no performance gain. In addition there were some errors in the plugins which don't occur for single worker instance. After taking above into consideration we decided to skip this feature

**Pull request closed without merging**
