### PR TITLE
add resource limits for prometheus container

### LINKED ISSUE #885: Prometheus container has no limits set by default

### PR DESCRIPTION
**Pull request by vsinghal13**
###### Description

Fixes #885 

###### Testing performed

- [ ] ci/build.sh
- [ ] Redeploy fluentd and fluentd-events pods
- [ ] Confirm events, logs, and metrics are coming in

### CODE REVIEW

**Review by perk-sumo — COMMENTED** [review]
I'd set the memory limit to 8Gb as we say in this doc that we've seen Prometheus go up to 5Gb; the worst thing we can have is to Prometheus get OOM killed.

**Review by frankreno — APPROVED** [review]
Agree with @perk then LGTM.

**Review by perk-sumo — APPROVED** [review]
👍

**Review by sumo-drosiek — APPROVED** [review]

**Comment by vsinghal13** [comment]
Closing in favor of #959

**Pull request closed without merging**
